# Generated by Django 4.0 on 2021-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(default='fix-me', max_length=254, unique=True, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='autor',
            name='password',
            field=models.CharField(default='fix-me', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='username',
            field=models.CharField(default='fix-me', max_length=100, unique=True, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autor',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellidos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos de Autor'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres de Autor'),
        ),
    ]
